VERSION_REGISTRY = {
    'v2.0': 'run_full_pipeline_v2.py',
    'v3.0': 'run_full_pipeline_v3.py',
    'v3.1': 'run_full_pipeline_v3.1.py',
    'v3.2': 'run_full_pipeline_v3.2.py',
    'v3.3': 'run_full_pipeline_v3.3.py',
    'v3.4': 'run_full_pipeline_v3.4.py',
    'v3.5': 'run_full_pipeline_v3.5.py',
    'v3.6': 'run_full_pipeline_v3.6.py',
    'v3.7': 'run_full_pipeline_v3.7.py',
    'v3.8': 'run_full_pipeline_v3.8.py',
    'v3.9':  'run_full_pipeline_v3.9.py',
    'v3.95': 'run_full_pipeline_v3.95.py',
    'v4.0':  'run_full_pipeline_v4.0.py',
    'v4.1':  'run_full_pipeline_v4.1.py',
    'v4.2':  'run_full_pipeline_v4.2.py',
    'v4.3':  'run_full_pipeline_v4.3.py',
    'v4.31': 'run_full_pipeline_v4.31.py',
    'v4.32': 'run_full_pipeline_v4.32.py',
    'v4.33': 'run_full_pipeline_v4.33.py',
    'v4.35': 'run_full_pipeline_v4.35.py',
    'v4.4':  'run_full_pipeline_v4.4.py',
    'v4.5':  'run_full_pipeline_v4.5.py',
    'v4.6':  'run_full_pipeline_v4.6.py',
}

PIPELINE_VERSION = 'v4.6'
PIPELINE_SCRIPT  = VERSION_REGISTRY[PIPELINE_VERSION]

# All files that must be present on the cluster for any pipeline run.
# Includes: core modules (auto-discovered via import tracing), all versioned
# stage3 detection modules, all pipeline scripts, and the SLURM job script.
CLUSTER_MANIFEST = [
    # Model catalogue JSONs — must stay in sync with code changes
    'diffusion_models.json',
    'noise_models.json',
    # Core pipeline modules
    'pipeline.py',
    'measurement.py',
    'model_registry.py',
    'model_classes.py',
    'fcs_io.py',
    'raw_io.py',
    'compute_features.py',
    'compute_features_multidt.py',
    'version.py',
    # Stage 3 detection modules — one per pipeline version that changes stage3
    'stage3_v2.py',
    'stage3_v3_1.py',
    'stage3_v3_2.py',
    'stage3_v3_3.py',
    'stage3_v3_4.py',
    'stage3_v3_5.py',
    'stage3_v3_6.py',
    'stage3_v3_7.py',
    'stage3_v3_8.py',
    'stage3_v3_9.py',
    'stage3_v3_95.py',
    'stage3_v4.py',
    'stage3_v4_1.py',
    'stage3_v4_2.py',
    'stage3_v4_3.py',
    'stage3_v4_4.py',
    # All pipeline scripts
    'run_full_pipeline_v2.py',
    'run_full_pipeline_v3.py',
    'run_full_pipeline_v3.1.py',
    'run_full_pipeline_v3.2.py',
    'run_full_pipeline_v3.3.py',
    'run_full_pipeline_v3.4.py',
    'run_full_pipeline_v3.5.py',
    'run_full_pipeline_v3.6.py',
    'run_full_pipeline_v3.7.py',
    'run_full_pipeline_v3.8.py',
    'run_full_pipeline_v3.9.py',
    'run_full_pipeline_v3.95.py',
    'run_full_pipeline_v4.0.py',
    'run_full_pipeline_v4.1.py',
    'run_full_pipeline_v4.2.py',
    'run_full_pipeline_v4.3.py',
    'run_full_pipeline_v4.31.py',
    'run_full_pipeline_v4.32.py',
    'run_full_pipeline_v4.33.py',
    'run_full_pipeline_v4.35.py',
    'run_full_pipeline_v4.4.py',
    'run_full_pipeline_v4.5.py',
    'run_full_pipeline_v4.6.py',
    # SLURM job script
    'job_full_pipeline_with_plots.sh',
]
